### ISSUE TITLE
Add checks that columns relevant to the light curve class that must be in there to run have checks that they exist

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/sorcha_community_utils#5]
I think we should push the burden on these added functions to check that the relevant data frame columns exist since in the main bits of sorcha when the input files are initially read in, we won't know what columns are missing.

**Comment by drewoldag** [comment]
I believe that this is taken care of in PR #4. The user defined lightcurve or comet activity class also specifies which columns are required in the observations dataframe. 

Before any computation happens, we make a call to `self._validate_column_names()` if the required column names are not present in the provided dataframe we'll raise an exception and log an error and raise and exception. 

If that's insufficient, (or perhaps the incorrect action to take) then we can reopen this issue and address it in a different way.

**Comment by mschwamb** [comment]
Yep it is.
